### ISSUE TITLE
Cannot import 'Self' from 'typing' (python3.9)

### ISSUE THREAD

**Issue by sielski666** [PaulMarisOUMary/Discord-Bot#141]
18.11 11:23:01 [Bot] Traceback (most recent call last):
18.11 11:23:01 [Bot] File "/bot.py", line 4, in <module>
18.11 11:23:01 [Bot] from classes.discordbot import DiscordBot
18.11 11:23:01 [Bot] File "/classes/discordbot.py", line 7, in <module>
18.11 11:23:01 [Bot] from typing import List, Self
18.11 11:23:01 [Bot] ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.9/typing.py)

**Comment by PaulMarisOUMary** [comment]
Thanks for the report, the problem has been identified and I'm working on a fix that will be available soon.
